# Questionnaire Analysis

Code to analyze the questionnaire responses: calculate metrics, match them to tasks.

In [1]:
from shared import *
import pandas


def map_agreement(agreement):
    if agreement == "Strongly agree":
        return 5
    elif agreement == "Agree":
        return 4
    elif agreement == "Neutral":
        return 3
    elif agreement == "Disagree":
        return 2
    elif agreement == "Strongly disagree":
        return 1
    return agreement

def drop_unneeded(dataframe):
    return dataframe.drop(["Start time", "Completion time", "Email", "Name", "Last modified time"], axis=1)


def preprocess(dataframe):
    dataframe = drop_unneeded(dataframe)
    dataframe = dataframe.map(map_agreement)
    return dataframe

evaluation_data = pandas.read_csv("./questionnaire_data/Evaluation_Feedback.csv", sep=";")
evaluation_data = preprocess(evaluation_data)
overall_data = pandas.read_csv("./questionnaire_data/Overall_Feedback.csv", sep=";")
overall_data = preprocess(overall_data)

In [2]:
excluded_participant_id = "P2" # strong outlier -> ignore

filtered_evaluation_data = evaluation_data[evaluation_data["ID"] != excluded_participant_id]
filtered_overall_data = overall_data[overall_data["ID"] != excluded_participant_id]

In [3]:
filtered_evaluation_data.describe()

,"When using the extension, it helped me to find relevant locations in the code for the first time.","When using the extension, it helped me to find again already visited code locations.","When using the extension, it helped me to keep track of relevant code locations.","When using the extension, it helped me to reduce the time to navigate to other relevant code locations.","When using the extension, it helped me to retain my thought process or concentration when (trying to) navigate to relevant code locations."
count,7.000000,7.000000,7.000000,7.000000,7.000000
mean,3.285714,3.857143,3.714286,3.142857,3.714286
std,1.380131,0.899735,0.755929,1.214986,0.951190
min,1.000000,3.000000,3.000000,2.000000,2.000000
25%,2.500000,3.000000,3.000000,2.000000,3.500000
50%,4.000000,4.000000,4.000000,3.000000,4.000000
75%,4.000000,4.500000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000

In [4]:
filtered_overall_data.describe()

,"In general, I think the extension would help me to find relevant locations in the code for the first time.","In general, I think the extension would help me to find again already visited code locations.","In general, I think the extension would help me to keep track of relevant code locations.","In general, I think the extension would reduce my time to navigate to other relevant code locations.","In general, I think the extension would help me to retain my thought process or concentration when (trying to) navigate to relevant code locations.",I liked using the extension.,I would use the navigation part of the extension again.,I would use the histogram part of the extension again.,I would use the method view of the extension again.
count,8.000000,8.000000,8.000000,8.000000,8.00000,7.000000,8.000000,8.000000,8.00000
mean,3.125000,4.250000,4.000000,3.875000,4.12500,4.142857,4.000000,3.625000,3.75000
std,1.356203,0.707107,0.755929,1.125992,0.64087,0.690066,1.069045,0.744024,0.46291
min,1.000000,3.000000,3.000000,2.000000,3.00000,3.000000,2.000000,3.000000,3.00000
25%,2.000000,4.000000,3.750000,3.000000,4.00000,4.000000,3.750000,3.000000,3.75000
50%,3.500000,4.000000,4.000000,4.000000,4.00000,4.000000,4.000000,3.500000,4.00000
75%,4.000000,5.000000,4.250000,5.000000,4.25000,4.500000,5.000000,4.000000,4.00000
max,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,4.00000

In [5]:
task_one_participant_ids = [participant.name for participant in participants if participant.evalTask == EvaluationTask.T1]
task_two_participant_ids = [participant.name for participant in participants if participant.evalTask == EvaluationTask.T2]

evaluation_task_one = filtered_evaluation_data[filtered_evaluation_data.apply(lambda row: row["ID"] in task_one_participant_ids, axis=1)]
evaluation_task_two = filtered_evaluation_data[filtered_evaluation_data.apply(lambda row: row["ID"] in task_two_participant_ids, axis=1)]
overall_task_one = filtered_overall_data[filtered_overall_data.apply(lambda row: row["ID"] in task_one_participant_ids, axis=1)]
overall_task_two = filtered_overall_data[filtered_overall_data.apply(lambda row: row["ID"] in task_two_participant_ids, axis=1)]

In [6]:
evaluation_task_one.describe()

,"When using the extension, it helped me to find relevant locations in the code for the first time.","When using the extension, it helped me to find again already visited code locations.","When using the extension, it helped me to keep track of relevant code locations.","When using the extension, it helped me to reduce the time to navigate to other relevant code locations.","When using the extension, it helped me to retain my thought process or concentration when (trying to) navigate to relevant code locations."
count,5.000000,5.0,5.00000,5.000000,5.000000
mean,3.800000,4.0,3.80000,3.400000,3.800000
std,1.095445,1.0,0.83666,1.341641,1.095445
min,2.000000,3.0,3.00000,2.000000,2.000000
25%,4.000000,3.0,3.00000,2.000000,4.000000
50%,4.000000,4.0,4.00000,4.000000,4.000000
75%,4.000000,5.0,4.00000,4.000000,4.000000
max,5.000000,5.0,5.00000,5.000000,5.000000

In [7]:
evaluation_task_two.describe()

,"When using the extension, it helped me to find relevant locations in the code for the first time.","When using the extension, it helped me to find again already visited code locations.","When using the extension, it helped me to keep track of relevant code locations.","When using the extension, it helped me to reduce the time to navigate to other relevant code locations.","When using the extension, it helped me to retain my thought process or concentration when (trying to) navigate to relevant code locations."
count,2.000000,2.000000,2.000000,2.000000,2.000000
mean,2.000000,3.500000,3.500000,2.500000,3.500000
std,1.414214,0.707107,0.707107,0.707107,0.707107
min,1.000000,3.000000,3.000000,2.000000,3.000000
25%,1.500000,3.250000,3.250000,2.250000,3.250000
50%,2.000000,3.500000,3.500000,2.500000,3.500000
75%,2.500000,3.750000,3.750000,2.750000,3.750000
max,3.000000,4.000000,4.000000,3.000000,4.000000

In [8]:
overall_task_one.describe()

,"In general, I think the extension would help me to find relevant locations in the code for the first time.","In general, I think the extension would help me to find again already visited code locations.","In general, I think the extension would help me to keep track of relevant code locations.","In general, I think the extension would reduce my time to navigate to other relevant code locations.","In general, I think the extension would help me to retain my thought process or concentration when (trying to) navigate to relevant code locations.",I liked using the extension.,I would use the navigation part of the extension again.,I would use the histogram part of the extension again.,I would use the method view of the extension again.
count,5.000000,5.000000,5.00000,5.00000,5.000000,5.00000,5.000000,5.000000,5.000000
mean,3.200000,4.000000,3.80000,3.80000,3.800000,4.20000,4.000000,3.400000,3.800000
std,1.643168,0.707107,0.83666,1.30384,0.447214,0.83666,1.224745,0.547723,0.447214
min,1.000000,3.000000,3.00000,2.00000,3.000000,3.00000,2.000000,3.000000,3.000000
25%,2.000000,4.000000,3.00000,3.00000,4.000000,4.00000,4.000000,3.000000,4.000000
50%,4.000000,4.000000,4.00000,4.00000,4.000000,4.00000,4.000000,3.000000,4.000000
75%,4.000000,4.000000,4.00000,5.00000,4.000000,5.00000,5.000000,4.000000,4.000000
max,5.000000,5.000000,5.00000,5.00000,4.000000,5.00000,5.000000,4.000000,4.000000

In [9]:
overall_task_two.describe()

,"In general, I think the extension would help me to find relevant locations in the code for the first time.","In general, I think the extension would help me to find again already visited code locations.","In general, I think the extension would help me to keep track of relevant code locations.","In general, I think the extension would reduce my time to navigate to other relevant code locations.","In general, I think the extension would help me to retain my thought process or concentration when (trying to) navigate to relevant code locations.",I liked using the extension.,I would use the navigation part of the extension again.,I would use the histogram part of the extension again.,I would use the method view of the extension again.
count,3.0,3.000000,3.000000,3.0,3.000000,2.0,3.0,3.0,3.000000
mean,3.0,4.666667,4.333333,4.0,4.666667,4.0,4.0,4.0,3.666667
std,1.0,0.577350,0.577350,1.0,0.577350,0.0,1.0,1.0,0.577350
min,2.0,4.000000,4.000000,3.0,4.000000,4.0,3.0,3.0,3.000000
25%,2.5,4.500000,4.000000,3.5,4.500000,4.0,3.5,3.5,3.500000
50%,3.0,5.000000,4.000000,4.0,5.000000,4.0,4.0,4.0,4.000000
75%,3.5,5.000000,4.500000,4.5,5.000000,4.0,4.5,4.5,4.000000
max,4.0,5.000000,5.000000,5.0,5.000000,4.0,5.0,5.0,4.000000

In [ ]:
high_java_experience_participant_ids = ["P1", "P2", "P6", "P8"]
high_vscode_experience_participant_ids = ["P3", "P5", "P8"]

In [ ]:
overall_java_experienced = overall_data[overall_data.apply(lambda row: row["ID"] in high_java_experience_participant_ids, axis=1)]
overall_java_experienced.describe()

,"In general, I think the extension would help me to find relevant locations in the code for the first time.","In general, I think the extension would help me to find again already visited code locations.","In general, I think the extension would help me to keep track of relevant code locations.","In general, I think the extension would reduce my time to navigate to other relevant code locations.","In general, I think the extension would help me to retain my thought process or concentration when (trying to) navigate to relevant code locations.",I liked using the extension.,I would use the navigation part of the extension again.,I would use the histogram part of the extension again.,I would use the method view of the extension again.
count,4.00,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.00000,4.00
mean,2.25,3.750000,3.000000,3.000000,3.000000,4.000000,3.000000,3.50000,3.75
std,1.50,1.892969,1.414214,1.632993,1.414214,0.816497,1.825742,0.57735,0.50
min,1.00,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,3.00000,3.00
25%,1.00,3.250000,2.500000,2.500000,2.500000,3.750000,1.750000,3.00000,3.75
50%,2.00,4.500000,3.500000,3.000000,3.500000,4.000000,3.000000,3.50000,4.00
75%,3.25,5.000000,4.000000,3.500000,4.000000,4.250000,4.250000,4.00000,4.00
max,4.00,5.000000,4.000000,5.000000,4.000000,5.000000,5.000000,4.00000,4.00

In [ ]:
overall_vscode_experienced = overall_data[overall_data.apply(lambda row: row["ID"] in high_vscode_experience_participant_ids, axis=1)]
overall_vscode_experienced.describe()

,"In general, I think the extension would help me to find relevant locations in the code for the first time.","In general, I think the extension would help me to find again already visited code locations.","In general, I think the extension would help me to keep track of relevant code locations.","In general, I think the extension would reduce my time to navigate to other relevant code locations.","In general, I think the extension would help me to retain my thought process or concentration when (trying to) navigate to relevant code locations.",I liked using the extension.,I would use the navigation part of the extension again.,I would use the histogram part of the extension again.,I would use the method view of the extension again.
count,3.0,3.000000,3.000000,3.0,3.000000,2.0,3.0,3.0,3.000000
mean,3.0,4.666667,4.333333,4.0,4.666667,4.0,4.0,4.0,3.666667
std,1.0,0.577350,0.577350,1.0,0.577350,0.0,1.0,1.0,0.577350
min,2.0,4.000000,4.000000,3.0,4.000000,4.0,3.0,3.0,3.000000
25%,2.5,4.500000,4.000000,3.5,4.500000,4.0,3.5,3.5,3.500000
50%,3.0,5.000000,4.000000,4.0,5.000000,4.0,4.0,4.0,4.000000
75%,3.5,5.000000,4.500000,4.5,5.000000,4.0,4.5,4.5,4.000000
max,4.0,5.000000,5.000000,5.0,5.000000,4.0,5.0,5.0,4.000000

In [ ]:
overall_vscode_not_experienced = overall_data[overall_data.apply(lambda row: row["ID"] not in high_vscode_experience_participant_ids, axis=1)]
overall_vscode_not_experienced.describe()